"""empty message

Revision ID: 131ad05d4ca8
Revises: 9fcbca679d7e
Create Date: 2023-03-07 15:07:57.942377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '131ad05d4ca8'
down_revision = '9fcbca679d7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
