"""empty message

Revision ID: 60df98850f95
Revises: 990939dbde61
Create Date: 2023-03-16 22:01:19.213145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60df98850f95'
down_revision = '990939dbde61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_hash', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar_hash')

    # ### end Alembic commands ###
